name: Docker deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploying images to VM
        uses: appleboy/ssh-action@v0.1.10
        env:
          CR_REGISTRY: crpd1r3n8uh8in4v12sv
          CR_REPOSITORY: git-hub-actions
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ssh-agent -t 1h
            ssh-add - <<<"${{ secrets.SSH_PRIVATE_KEY }}"
            ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
              cd ~/Github-action_testing/project
              sudo docker stop $(sudo docker ps -a -q)
              sudo docker rm $(sudo docker ps -a -q)
              git pull
              sudo docker-compose up -d
            EOF
